//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ramesoft.Cms.Common.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Histories = new HashSet<History>();
            this.Products = new HashSet<Product>();
        }
    
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
    
        public virtual ICollection<History> Histories { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
