//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ramesoft.Cms.Common.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public Log()
        {
            this.Log1 = new HashSet<Log>();
        }
    
        public int LogId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string LogLevel { get; set; }
        public string Message { get; set; }
        public string Exception { get; set; }
        public string StackTrace { get; set; }
        public Nullable<int> InnerException { get; set; }
    
        public virtual ICollection<Log> Log1 { get; set; }
        public virtual Log Log2 { get; set; }
    }
}
