//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ramesoft.Cms.Common.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int OrderID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<int> ShipCompanyID { get; set; }
        public Nullable<decimal> Discount { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Company Company1 { get; set; }
        public virtual ContactPerson ContactPerson { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
