//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ramesoft.Cms.Common.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string UnitName { get; set; }
        public Nullable<short> UnitScale { get; set; }
        public Nullable<int> InStock { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> DiscontinuedPrice { get; set; }
        public Nullable<bool> Discontinued { get; set; }
        public Nullable<int> CompanyId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Company Company { get; set; }
    }
}
